spring.application.name=libraryMs
spring.datasource.url=jdbc:postgresql://localhost:5432/libraryMs
spring.datasource.username=postgres
spring.datasource.password=123eeecan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
